export const RoleUser = {
  CUSTOMER: "CUSTOMER",
  SALLER: "SALLER",
  ADMIN: "ADMIN",
};
export const TypeProduct = {
  TREE_IN_DOOR: "TREE_IN_DOOR",
  TREE_OUT_DOOR: "TREE_OUT_DOOR",
  KITS: "KITS",
  FERTILIZER: "FERTILIZER",
  COURSE: "COURSE",
};
export const Filter = {
  ALL: "ALL",
  LESS_50: "LESS_50",
  MORE_50: "MORE_50",
  LESS_20: "LESS_20",
  NEW_TIME: "NEW_TIME",
  OLD_TIME: "OLD_TIME",
  LESS_MONEY: "LESS_MONEY",
  MORE_MONEY: "MORE_MONEY",
  AWAIT_MOMO: "AWAIT_MOMO",
  MOMO: "AWAIT_MOMO",
  UNPAID: "UNPAID",
  PAID: "PAID",
  SUCCESS: "SUCCESS",
};
export const StatusPayment = {
  AWAIT_MOMO: "AWAIT_MOMO",
  MOMO: "AWAIT_MOMO",
  UNPAID: "UNPAID",
  PAID: "PAID",
  SUCCESS: "SUCCESS",
};

export const StatusOrder = {
  PREPARE: "PREPARE",
  CONFIRM: "CONFIRM",
  DELIVERY_SHIP: "DELIVERY_SHIP",
  SHIP: "SHIP",
  REVEICE: "REVEICE",
  SUCCESS: "SUCCESS",
  CANCEL: "CANCEL",
  NOT_CONFIRMED: "NOT_CONFIRMED",
};
export const TypePayment = {
  MOMO: "MOMO",
  DIRECT: "DIRECT",
};
